#!/bin/bash


### Job Name
#SBATCH --job-name=PerformExperiments

### Set email type for job
### Accepted options: NONE, BEGIN, END, FAIL, ALL
#SBATCH --mail-type=END

### email address for user
###SBATCH --mail-user=None

### Queue name that job is submitted to
#SBATCH --partition=tango

### Request resources
#SBATCH --ntasks=4
#SBATCH --mem=64gb

echo Running on host `hostname`
echo Time is `date`

Rscript DAGTurnOver.R
Rscript DoExTurnOver.R
Rscript DoExTurnOverSurv.R

Rscript DAGAdult.R
Rscript DoExAdult.R

python GenerateResults.py

Rscript SurvML.R
